openapi: 3.1.0
info:
  title: Booksim Runner
  description: Run NoC simulations via Booksim using natural language-generated configs.
  version: 1.0.0
servers:
  - url: https://bookin-wgvp.onrender.com
paths:
  /run-generated-config:
    post:
      summary: Run Generated Config
      operationId: run_generated_config_run_generated_config_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeneratedConfigRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /openapi.yaml:
    get:
      summary: Serve Openapi Yaml
      operationId: serve_openapi_yaml_openapi_yaml_get
      responses:
        '200':
          description: Successful Response
          content:
            text/plain:
              schema:
                type: string
  /logo.png:
    get:
      summary: Get Logo
      operationId: get_logo_logo_png_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /legal:
    get:
      summary: Legal Info
      operationId: legal_info_legal_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
components:
  schemas:
    GeneratedConfigRequest:
      properties:
        config_str:
          type: string
          title: Config Str
      type: object
      required:
      - config_str
      title: GeneratedConfigRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
